name: follow-user-microservice CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven Packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-${{ runner.os }}

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Run Unit Tests
        run: mvn test

  docker-build:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t follow-user-microservice:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{{{ secrets.DOCKER_HUB_USERNAME }}}}
          password: ${{{{ secrets.DOCKER_HUB_ACCESS_TOKEN }}}}

      - name: Push Docker Image
        run: |
          docker tag follow-user-microservice:latest ${{{{ secrets.DOCKER_HUB_USERNAME }}}}/follow-user-microservice:latest
          docker push ${{{{ secrets.DOCKER_HUB_USERNAME }}}}/follow-user-microservice:latest

  deploy:
    needs: docker-build
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{{{ secrets.SERVER_HOST }}}}
          username: ${{{{ secrets.SERVER_USER }}}}
          key: ${{{{ secrets.SERVER_SSH_KEY }}}}
          script: |
            docker pull ${{{{ secrets.DOCKER_HUB_USERNAME }}}}/follow-user-microservice:latest
            docker stop follow-user-microservice || true
            docker rm follow-user-microservice || true
            docker run -d --name follow-user-microservice -p 8080:8080 ${{{{ secrets.DOCKER_HUB_USERNAME }}}}/follow-user-microservice:latest
